version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - ./.data/mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-u', 'root']
      interval: 1s
      timeout: 3s
      retries: 3
    env_file:
      - .env
    expose:
      - 3306

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"

  django:
    container_name: django
    build: ./api
    volumes:
      - ./api:/var/lib/django/api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    expose:
      - 8000

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      args:
        REACT_SERVER_NAME: ${REACT_SERVER_NAME}
        DJANGO_SERVER_NAME: ${DJANGO_SERVER_NAME}
        REACT_SERVER_PORT: ${REACT_SERVER_PORT}
        DJANGO_SERVER_PORT: ${DJANGO_SERVER_PORT}
    volumes:
      - ./api/static:/var/lib/nginx/static
    depends_on:
      - django
    ports:
      - "80:80"
      - "8000:8000"
